# Site settings
title: Jesús López
email: inyenia@gmail.com
url: https://inyenia.github.io
description: "La informática es mi hobby, mi profesión y mi pasión. Soy un afortunado usuario y desarrollador de software. Me apasionan las nuevas tecnologías, los móviles y afrontar nuevos retos."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: CA3A3A #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: inyenia
  location: Sevilla, España
  social: Yo en las redes sociales
  credits: Créditos

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/inyenia
  - title: facebook
    url: https://es-es.facebook.com/inyenia
  - title: stack-overflow
    url: http://stackoverflow.com/users/4046750/inyenia
  - title: linkedin
    url: https://es.linkedin.com/in/inyenia
  - title: github
    url: http://github.com/inyenia

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
